### ISSUE TITLE
Buttons missing

### ISSUE THREAD

**Issue by xxCoolxx18** [CapnKitten/Spotify-Discord#1]
The Minimize, Maximize and Close buttons are missing http://prntscr.com/kngg6h

**Comment by CapnKitten** [comment]
I'm not able to replicate the problem. Are you using any plugins that I might have to add support for?

**Comment by xxCoolxx18** [comment]
Not that i know of.

**Comment by CapnKitten** [comment]
That's weird, because no one else has had issues with the window buttons.

**Comment by xxCoolxx18** [comment]
Let me try something. I'll keep in tact.

**Comment by xxCoolxx18** [comment]
Do you think it could be this? https://github.com/intrnl/discordcustomizations/tree/master/titlebarRevert

**Comment by CapnKitten** [comment]
That's the culprit. There's a plugin by mwittrien that adds the old title bar, if you'd like to use that instead.

https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/OldTitleBar
