### ISSUE TITLE
New Discord Upate

### ISSUE THREAD

**Issue by refrsh-ok** [CapnKitten/Spotify-Discord#11]
The new Discord update has broken a few things... I don't have screenshots since there's so much broken, but I can tell you what I noticed right away:
- The "Jump to present" button has broken.
- Pings are colored normally.
- New GUI elements don't have the theme colors.

That's it, hope you can fix it as soon as you can!

**Comment by CapnKitten** [comment]
Not sure which version of the theme you're using, but most of the recent Discord changes have been updated. You are right about the jump to present and mentions though.

**Comment by CapnKitten** [comment]
Fixes are live with v1.3.2
