### ISSUE TITLE
Missing search navigation

### ISSUE THREAD

**Issue by zzinggame** [CapnKitten/Spotify-Discord#12]
When i use this theme, the "previous" and "next" button in search is gone, it normal when i don't use this theme.

**Comment by CapnKitten** [comment]
It appears that Discord updated the class names for no reason at all again. I'll get it fixed as soon as I can, thanks.

**Comment by CapnKitten** [comment]
Issue is fixed in v1.3.5.1.

**Comment by zzinggame** [comment]
The issue still exist
