### ISSUE TITLE
The theme wont go away.

### ISSUE THREAD

**Issue by oFrogi** [CapnKitten/Spotify-Discord#20]
Ive uninstalled the theme, deleted it completly, and toggled it off, repaired BD, and it just wont go away, Please help.
![image](https://user-images.githubusercontent.com/83510199/116789057-0403f680-aa7b-11eb-9480-14b8dce813b3.png)

**Comment by CapnKitten** [comment]
Which version of BetterDiscord are you using, and have you tried just uninstalling it then reinstalling it?

**Comment by oFrogi** [comment]
I uninstalled it just now, it STILL hasnt gone away. Im using the latest version, from the new site.

**Comment by CapnKitten** [comment]
Something is messed up. Have you tried uninstalling Discord?

**Comment by oFrogi** [comment]
No, ill try that now.

**Comment by oFrogi** [comment]
update: I uninstalled Discord as a whole, the whole client. Relaunched it, and reinstalled BD into it. The theme was still there.

**Comment by CapnKitten** [comment]
Alright, follow these steps to see if the theme is still in the html.

1. Ctrl + shift + i to open the dev console in discord.
2. Click the arrow next to the `<head>...</head>` tags to open it.
3. Scroll down until you see `<bd-head>...</bd-head>` (it should be right below a list of `<script>` tags) and open it
4. Open `<bd-themes>...</bd-themes>` and see if you see a line like `<style id="Spotify_Discord">...</style>`
5. If you see it, right click on it and click delete element. If you don't see it, then I have no idea.

**Comment by oFrogi** [comment]
Thank you! This worked! Your so nice and helpful :D
