### ISSUE TITLE
Theme conflicting with ''Radial Status''

### ISSUE THREAD

**Issue by TejaFX2108** [CapnKitten/Spotify-Discord#22]
Love the new design! The friends list looks really nice but after the last update it started conflicting with the Radial Status add-on. Is there a way to fix this?
![yes](https://user-images.githubusercontent.com/83318842/117314525-23d65880-ae87-11eb-82f8-5def639738f9.PNG)

**Comment by CapnKitten** [comment]
Got this fixed, just restart your discord client to get the update.
