### ISSUE TITLE
Issue with  volume scroll

### ISSUE THREAD

**Issue by dopekilla** [CapnKitten/Spotify-Discord#24]
**
![image](https://user-images.githubusercontent.com/32855137/117545004-1fbe4e00-afe1-11eb-8545-757bc902c592.png)
**

**Comment by dopekilla** [comment]
there is also another issue with profile colors 
![image](https://user-images.githubusercontent.com/32855137/117545055-6c098e00-afe1-11eb-9747-6e45b363c76d.png)

**Comment by CapnKitten** [comment]
I'll get the slide knob position fixed, but the blue color is as intended when someone is playing a game.

**Comment by dopekilla** [comment]
aight thx
