### ISSUE TITLE
DM confirmations not showing up correctly

### ISSUE THREAD

**Issue by Floyddo** [CapnKitten/Spotify-Discord#30]
When getting dm'ed by a user that you have never dm'ed with before a confirmation shows up, with this theme it blocks it out
![image (4)](https://user-images.githubusercontent.com/94007468/140974863-432e1095-e011-44fb-8a5a-43eb12da0707.png)
![image (27)](https://user-images.githubusercontent.com/94007468/140974869-4c08b5b7-46b5-49f8-8331-56ff9e2a0a64.jpg)
.

**Comment by CapnKitten** [comment]
It's due to the bottom bar. I'll get it fixed, thanks.
