### ISSUE TITLE
certain elements are unthemed (possible partial class reshuffling?)

### ISSUE THREAD

**Issue by akirapink** [CapnKitten/Spotify-Discord#31]
![image](https://user-images.githubusercontent.com/33667869/166561783-1b20b2f4-60cb-40b4-960f-69db5506f2cf.png)
the main column background, the bg of popups like the upload file button's, the button bar on the left side of messages, the user popout are all fucked

**Comment by CapnKitten** [comment]
I'm not so sure that it's a discord update causing it because I can't reproduce it on both stable and canary. It could be related to the discord linux client.

**Comment by TPO100Cofficial** [comment]
ah, yeah, i am on linux
should've mentioned, sorry
is thsi an unsolvable problem, or...?

**Comment by CapnKitten** [comment]
Are other themes working properly?
