### ISSUE TITLE
Friend list UI is not the same as it should be

### ISSUE THREAD

**Issue by reynoldyehezkiel** [CapnKitten/Spotify-Discord#32]
The UI is not the same
![image](https://user-images.githubusercontent.com/73789263/180730254-b633f889-4cec-4b3f-9247-2b0ba8d5c4e3.jpeg)

**Comment by CapnKitten** [comment]
The friends list pictured in the preview screenshots was scrapped a while back due to many people having a scrolling issue that I was unable to replicate, and thus unable to fix.

**Comment by reynoldyehezkiel** [comment]
Ok, thx for the explanation
