### ISSUE TITLE
Plugin and themes aren't working properly

### ISSUE THREAD

**Issue by ReconExe** [CapnKitten/Spotify-Discord#33]
My profile is not at the top, and the spotify plugin should be a little bit below.
Im using windows 10 and i have the last theme and plugin.

Please help me ^^'

![Capture d’écran (280)(1)](https://user-images.githubusercontent.com/68652744/226100165-983156e8-0934-436d-a0ea-08b68088afce.jpg)

**Comment by CapnKitten** [comment]
You need to use the redesign addon located [here](https://github.com/CapnKitten/BetterDiscord/tree/master/Themes/Spotify-Discord/css/addons/redesign).

**Comment by ReconExe** [comment]
How do i do that ?

**Comment by ReconExe** [comment]
Thanks !
