### ISSUE TITLE
Streamer Mode breaks UI

### ISSUE THREAD

**Issue by chloecdn** [CapnKitten/Spotify-Discord#35]
Enabling Streamer-Mode (Or having it enable automatically) will cause the Mute/Deafen Symbol to align incorrectly. Nothing major, but just so you know.

![image](https://github.com/CapnKitten/Spotify-Discord/assets/80840951/cc4cc9ae-1f79-4b6f-87ff-ba03ab411425)

**Comment by chloecdn** [comment]
Note: This only appears whenever the purple top-bar is shown. Hiding it (difficult with how the mute-symbol is positioned, but not impossible) will "fix" it.

**Comment by CapnKitten** [comment]
A fix is live. Just restart your discord to get it.
