### ISSUE TITLE
[Bug] Black bar blocks bottom part of Discord

### ISSUE THREAD

**Issue by AGMShremp** [CapnKitten/Spotify-Discord#36]
Worked fine yesterday, then this appeared. I think the chat background is also a bit broken (it reverted to the default discord chat bg color).

Plugins:

BDFDB
SpotifyControls

![Bug  Picture](https://github.com/CapnKitten/Spotify-Discord/assets/101619251/420c49f7-912b-4be7-ad9a-a22e06d77e9f)

**Comment by ArchitectKev** [comment]
Got the same issue over here,
with devilbros spotify controls there seems  to be some extra issue since the 2 overlap the controls are barely functional anymore.

![image](https://github.com/CapnKitten/Spotify-Discord/assets/66266403/e99531bc-cdc1-4590-8dcf-89c4ddf8349a)

**Comment by Penguin-Terminal** [comment]
I am also experiencing the same issue as the original post. It just recently started happening, so it may be a problem with a discord update. I am currently running Vencord, not BetterDiscord, so it may also be just a compatibility thing.

**Comment by CapnKitten** [comment]
The theme has been updated to the new Spotify UI, which has fixed the issues caused by the Discord update. Restart your Discord client to get the update.
