### ISSUE TITLE
[Bug] Error messages are blocked by bar on top

### ISSUE THREAD

**Issue by achillesheelguy** [CapnKitten/Spotify-Discord#37]
I was in a VC with my friends with my microphone turned off. Normally, it would show on top that my microphone was muted but I noticed that it was blocked by the bar.

![image](https://github.com/CapnKitten/Spotify-Discord/assets/101619251/51271bfe-44ef-4ba6-bef1-120735100d10)

**Comment by BruhTacular** [comment]
Not a bug but unintended annoyance, the top bar covers channeltabs, which I use very frequently. Also personal preference, I am just not too fond of the bar on top as opposed to the bottom, might just be me though.
