### ISSUE TITLE
Theme stopped working? 

### ISSUE THREAD

**Issue by RadeusDood** [CapnKitten/Spotify-Discord#38]
This wasn't an issue until a while ago. When I pasted the raw link into the vencord online themes section, it didn't work. I checked using other themes, they seemed to work fine, its just this one. 
<img width="851" alt="Screenshot 2023-10-25 at 11 14 42 PM" src="https://github.com/CapnKitten/Spotify-Discord/assets/82723647/d144b37b-2edf-4390-ac3f-d455f012d4d9">

update: nvm just turns out vencord's broken. Sorry to bother! Im not sure how to close this.

**Comment by StevenKrahforst** [comment]
https://github.com/Vendicated/Vencord/issues/1847

**Comment by CapnKitten** [comment]
Discord update broke all themes by change every class name. It will take some time to get everything updated, but I am working on it.

**Comment by rbcoder117** [comment]
@RadeusDood, https://github.com/armcord/armcord, it has a new fix for it

**Comment by CapnKitten** [comment]
This has already been fixed, just didn't update this issue.
