### ISSUE TITLE
[Bug] Missing Mute, Deafen, and User Settings

### ISSUE THREAD

**Issue by Kederan** [CapnKitten/Spotify-Discord#5]
**Which plugin is this about?**
Spotify-Discord

**Describe the Bug**
When I activate the theme the user settings, mute and deafen button are missing next to my user name.

**To Reproduce**
Turning the plugin off and on.

**Expected Behavior**
To have the settings next to my username.

**Screenshots**
![Discord_2019-09-13_19-54-45](https://user-images.githubusercontent.com/19885815/64900789-4c319380-d661-11e9-9e3e-801ad395a17c.png)

**Discord Version**
Stable

**Comment by CapnKitten** [comment]
This has been fixed with the recent update (1.2.8.3).
