### ISSUE TITLE
My theme broke.

### ISSUE THREAD

**Issue by refrsh-ok** [CapnKitten/Spotify-Discord#8]
I don't know if it's Discord's fault but it's really annoying. The message box recently reverted to the default one. How can I fix this? (I tried reinstalling the theme).

![unknown](https://user-images.githubusercontent.com/59101714/71296213-1f3afe00-237f-11ea-8b31-43d117f07ddc.png)

**Comment by CapnKitten** [comment]
Discord updated and this is the result. I'll get a fix up soon.

**Comment by CapnKitten** [comment]
Update is live, refresh your client to get it.
